import "@/styles/globals.css";
import { Nunito } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  style: ["italic", "normal"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${nunito.className}`}>
      <body className="flex h-screen w-screen justify-center">
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
